install.packages('devtools')
install.packages('zoo')
install.packages('shiny')
install.packages('data.table')
install.packages('plyr')
install.packages('dplyr')
install.packages('testthat')
devtools::install_github("ebailey78/shinyBS")

install.packages('plotrix')
install.packages('ggplot2')
install.packages('multcomp')
devtools::install_github('sinhrks/ggfortify')
